# Generated by Django 4.2.11 on 2024-04-10 14:56

from django.db import migrations, models
import django.db.models.deletion
import grimoirelab.core.scheduler.models
import grimoirelab_toolkit.datetime


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fetchtask",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "new"),
                    (2, "enqueued"),
                    (3, "running"),
                    (4, "completed"),
                    (5, "failed"),
                    (6, "recovery"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    grimoirelab.core.scheduler.models.CreationDateTimeField(
                        default=grimoirelab_toolkit.datetime.datetime_utcnow,
                        editable=False,
                    ),
                ),
                (
                    "last_modified",
                    grimoirelab.core.scheduler.models.LastModificationDateTimeField(
                        default=grimoirelab_toolkit.datetime.datetime_utcnow,
                        editable=False,
                    ),
                ),
                ("job_id", models.CharField(max_length=128)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="scheduler.fetchtask",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
